const actionType = {
    FETCH_MOVIES_PENDING: 'FETCH_MOVIES_PENDING',
    FETCH_MOVIES_SUCCESS: 'FETCH_MOVIES_SUCCESS',
    FETCH_MOVIES_ERROR: 'FETCH_MOVIES_ERROR',
    FILTER_BY_GENRES: 'FILTER_BY_GENRES',
    SET_SORT_BY: 'SET_SORT_BY',
    SET_ORDER_BY: 'SET_ORDER_BY',
    SORT_MOVIES: 'SORT_MOVIES',
    ADD_MOVIE: 'ADD_MOVIE',
    UPDATE_MOVIE: 'UPDATE_MOVIE',
    DELETE_MOVIE: 'DELETE_MOVIE',
}

export default actionType;
