const actionType = {
    FETCH_MOVIES_PENDING: 'FETCH_MOVIES_PENDING',
    SET_MOVIES: 'SET_MOVIES',
    FETCH_MOVIES_ERROR: 'FETCH_MOVIES_ERROR',
    SET_FILTER_BY_GENRES: 'SET_FILTER_BY_GENRES',
    SET_SORT_BY: 'SET_SORT_BY',
    SET_SORT_ORDER: 'SET_SORT_ORDER',
}

export default actionType;
